
class StopEventLoop(Exception):
    pass


class TaskError(Exception):
    pass
